---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
