---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: loge -v
      command: lego -v  # noqa 301
      register: lego_v
    - name: ddd
      assert:
        that:
          - "'lego version 4.1.3' in lego_v.stdout"
